### ISSUE TITLE
./configure: 8: ./get-v8-linux.sh: Syntax error: redirection unexpected

### ISSUE THREAD

**Issue by pachadotdev** [jeroen/V8#162]
v 4.2.2. from CRAN fails on Ubuntu 20.04

**Comment by pachadotdev** [comment]
I meant: it can't be installed on Ubuntu 20.04 (i.e., on my laptop)

**Comment by jeroen** [comment]
There was a temporary problem bit it should be fixed now.

If you still have a problem and want me to help, please post the full install log .

**Comment by alexconrey** [comment]
Can we have some more information around the cause of the error? It seems like the logic used in this repo relies on the `master` branch and has no correlation to versioned releases.

**Comment by alexconrey** [comment]
It appears that the untracked, unsourced `get-v8-linux.sh` script referenced by the `configure` file changed from when I downloaded it yesterday:

```
alex@computer ~ % diff ~/Downloads/get-v8-linux.sh ~/Downloads/get-v8-linux\ \(1\).sh
8,9c8,9
< if grep -Fq "clang++" <<<"$CXX"; then
< if printf "#include <string>\n#ifndef _LIBCPP_VERSION\n#error not libcxx\n#endif" | $CXX -E -xc++ - > /dev/null 2>&1; then
---
> if echo "$CXX" | grep -Fq "clang"; then
> if printf "#include <string>\n#ifndef _LIBCPP_VERSION\n#error not libcxx\n#endif" | $CXX -E -xc++ - >/dev/null 2>&1; then
```

https://github.com/jeroen/V8/blob/master/configure#L88

This is calling a script that is not checked into source control: `http://jeroen.github.io/V8/get-v8-linux.sh` 

This is also problematic for users who wish to ensure dependencies are not compromised or otherwise tainted by pinning dependency versions. This really should be checked into git, both for audit/security purposes but also for pinning known good builds. We will need to pin to a revision if the trend of pushing directly to `master` is one this repo is going to continue following. 

Can you please do one of the following?
* Check `get-v8-linux.sh` into git and use GitHub's ability to render raw content from files (ie. https://raw.githubusercontent.com/jeroen/V8/master/configure)
* Stop pushing to `master` ?

**Comment by jeroen** [comment]
You can set `DISABLE_STATIC_LIBV8` at install time and link to `libv8-dev` on ubuntu if you prefer that.
