### ISSUE TITLE
Facing issue 'network unreachable' while trying to install V8 library in R code environment via Dataiku application

### ISSUE THREAD

**Issue by supriya-patha** [jeroen/V8#163]
Hi team,

We are trying to install V8 library in R code environment in Dataiku application but we are getting below error:
Error in curl::curl_download("http://jeroen.github.io/V8/get-v8-linux.sh",  : 
  Failed to connect to 2606:50c0:8002::153: Network is unreachable
We are performing this action with internet connectivity still facing this issue. Can you please help us with this issue?

Thanks

**Comment by jeroen** [comment]
Which linux distribution do you use?

**Comment by supriya-patha** [comment]
Hi jeroen,

We are not installing package using linux shell. We are installing it in dataiku application. We specify the package in the code environment and the application installs it. Please find the screenshot attached of the logs.

Thanks
<img width="799" alt="gt_issue" src="https://user-images.githubusercontent.com/123952503/215478519-1d0adaab-a968-4131-a444-2035c70b4d96.PNG">

**Comment by jeroen** [comment]
Did you try the suggestion at the bottom, to install `libv8-dev` or similar?

**Comment by laurejo1** [comment]
Similar issue on windows due to network restriction. As published on CRAN, is it expected to need external contents?

rm -f V8.dll RcppExports.o bindings.o
"C:/PROGRA~1/R/R-42~1.1/bin/x64/Rscript.exe" "../tools/ucrtlibs.R"
Error in download.file("https://github.com/jeroen/V8/releases/download/v3.6.0/v8-9.1.269.38-win-ucrt.pkg.tar.xz",  : 
  cannot open URL 'https://github.com/jeroen/V8/releases/download/v3.6.0/v8-9.1.269.38-win-ucrt.pkg.tar.xz'
