### ISSUE TITLE
v8 version

### ISSUE THREAD

**Issue by bhaskarvk** [jeroen/V8#36]
Any particular reason why v8 version can't be > 3.15 ?

**Comment by jeroen** [comment]
The `libv8` API keeps changing with each release. So we need to target a single version.

**Comment by bhaskarvk** [comment]
Cool, thanks for the clarification. It would be nice though if the package can keep up with libv8 from time to time, if not always the current version. 3.15 is way too old and later versions have not only performance benefits, but also allow you to code JS parts in ES6.

**Comment by jeroen** [comment]
I know that, but there is no other version of `libv8` included with most major distributions. 

So this would mean we would need to bundle `libv8` code with the R package, but unfortunately that will be very difficult because it requires custom google programs to build. I have tried but given up. 

Hopefully in the future there will either be a new "stable" version of `libv8` that becomes available on most major systems, or, they make it easier to bundle and build libv8 with the R package.

**Comment by bhaskarvk** [comment]
Bummer. Thanks for your explanation!
