### ISSUE TITLE
Update libv8

### ISSUE THREAD

**Issue by jeroen** [jeroen/V8#39]
The libv8 wiki [Getting-Started-with-Embedding](https://github.com/v8/v8/wiki/Getting-Started-with-Embedding). Have another look if libv8 can be bundled now.

**Comment by gracezhou0501** [comment]
Hi Jeroen,
How can I install libv8 for r on a linux server? My final goal is to install v8. 
When I run install.packages("libv8") in r, it gives me such error:
Warning in install.packages :
  package ‘libv8’ is not available (for R version 3.4.1)

Thank you very much for your help!
Grace

**Comment by jeroen** [comment]
You need to do `install.packages("V8")`

**Comment by gracezhou0501** [comment]
Thank you for your quick replay!
It gives me such errors:
>install.packages("V8")
Installing package into ‘/home/df4425/R/x86_64-redhat-linux-gnu-library/3.1’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/src/contrib/V8_1.5.tar.gz'
Content type 'application/x-gzip' length 327013 bytes (319 KB)
==================================================
downloaded 319 KB

* installing *source* package ‘V8’ ...
** package ‘V8’ successfully unpacked and MD5 sums checked
Using PKG_CFLAGS=-I/usr/include/v8-3.14
Using PKG_LIBS=-lv8
------------------------- ANTICONF ERROR ---------------------------
Configuration failed because  was not found. Try installing:
 * deb: libv8-3.14-dev (formerly: libv8-dev) (Debian, Ubuntu)
 * rpm: v8-314-devel (formerly: v8-devel) (Fedora, EPEL)
 * brew: v8@3.15 (OSX) -- NOT regular v8! Tap from homebrew/versions
 * csw: libv8_dev (Solaris)
To use a custom libv8, set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
--------------------------------------------------------------------
ERROR: configuration failed for package ‘V8’
* removing ‘/home/df4425/R/x86_64-redhat-linux-gnu-library/3.1/V8’
Warning in install.packages :
  installation of package ‘V8’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/RtmpwpfXtD/downloaded_packages’

**Comment by jeroen** [comment]
Yes so read that carefully. Depending on which linux you run you either need to:

```
sudo apt-get install libv8-3.14-dev
```
OR
```
sudo yum install v8-314-devel 
```

**Comment by gracezhou0501** [comment]
Awesome!!! Thank you very much! It works now. The problem is that I was not given access to sudoer file and I asked IT guy to give access and then run code you gave me in terminal to install livb8. Then I can install v8 in r successfully. Appreciate your time and your great package!

Best wishes,
Grace


Best,
Grace

**Comment by hrbrmstr** [comment]
I have some interest in using some of the newer features in later V8 engines from within R. There seems to be more than a few additional "moving parts" with the newer engines but if there's a dev branch you're working on let me know and I'll try to carve time out to help.

**Comment by jeroen** [comment]
Would [babel](https://github.com/babel/babel) help to compile code to be compatible? I'm a bit pessimistic about if I will ever be able to ship a the full libv8 in a way that can build on all platform and meet CRAN's standards.

**Comment by QuLogic** [comment]
I'd like to point out that `v8-314` does not compile on all arches supported by Fedora, so the shipped R-V8 also does not support all arches, though I'm not sure how much difference that makes to you. More importantly, there are about 30 patches just to build and the package is not building on F28 or Rawhide. I don't know how much longer the maintainer will be willing to keep it around, though at least there are 2 other packages using it, so there's some incentive other than R-V8.

Of course, I have no need for you to bundle everything...

**Comment by jeroen** [comment]
Right I'm crossing my fingers it will be around a bit more because there is no other version of libv8 that is available from all major distros. And bundling it with the R package would be a mess.

**Comment by hrbrmstr** [comment]
is there a potential way to side-step this and get it integrated via hacking with https://github.com/mattn/go-v8 ?

It is likely more complex but it may offload the bundling directly.

**Comment by znmeb** [comment]
This package no longer can install on Arch Linux. The AUR version of v8 3.14 doesn't build, their binary version of 3.14 installs but doesn't seem to have the include files, and their version of v8 3.15 doesn't build either.

**Comment by jeroen** [comment]
Have another look at the new API, maybe it has stabilized: https://github.com/v8/v8/blob/master/samples/hello-world.cc

**Comment by jeroen** [comment]
Making progress, discussion moved to: https://github.com/jeroen/V8/issues/48
