### ISSUE TITLE
Installing V8 on Gentoo

### ISSUE THREAD

**Issue by xfim** [jeroen/V8#94]
Dear @jeroen ,

I am trying to install V8 be able to update "rstan". It does not seem to work in my Gentoo laptop.

I am trying to play with the INCLUDE_DIR and LIB_DIR options but have not succeeded so far. The main problem, I imagine, is that I do not have v8 installed, and I am instead relying on nodejs (there are no official packages for v8 in gentoo, and the community contributed ones do not successfully install v8). 

My first question would be whether nodejs is enough for making "V8" work. These are the packages that "nodejs" installs in my computer:

```
/usr/include/node/v8-fast-api-calls.h
/usr/include/node/v8-internal.h
/usr/include/node/v8-platform.h
/usr/include/node/v8-profiler.h
/usr/include/node/v8-util.h
/usr/include/node/v8-value-serializer-version.h
/usr/include/node/v8-version-string.h
/usr/include/node/v8-version.h
/usr/include/node/v8-wasm-trap-handler-posix.h
/usr/include/node/v8-wasm-trap-handler-win.h
/usr/include/node/v8.h
/usr/include/node/v8config.h
/usr/include/node/deps/v8
/usr/include/node/deps/v8/include
/usr/include/node/libplatform/v8-tracing.h
```

The second question is about the specific command to install V8. The one that I think should work would be something like `R CMD INSTALL --configure-vars='INCLUDE_DIR=/usr/include/node/deps/v8/include LIB_DIR=/usr/include/node/libplatform' V8_3.2.0.tar.gz`, but it complains about libplatform not being found:

```
Found INCLUDE_DIR and/or LIB_DIR!
Using PKG_CFLAGS=-I/usr/include/node/deps/v8/include -I/usr/include/v8 -I/usr/include/v8-3.14
Using PKG_LIBS=-L/usr/include/node/libplatform -lv8 -lv8_libplatform
Running feature test for pointer compression...
/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lv8
/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lv8_libplatform
collect2: error: ld returned 1 exit status
Enabling pointer compression
** libs
rm -f V8.so RcppExports.o bindings.o
x86_64-pc-linux-gnu-g++ -std=gnu++11 -I"/usr/lib64/R/include" -DNDEBUG -I/usr/include/node/deps/v8/include -I/usr/include/v8 -I/usr/include/v8-3.14 -DV8_COMPRESS_POINTERS -I'/usr/lib64/R/library/R
cpp/include'   -fvisibility=hidden -fpic  -march=skylake -O3 -pipe -fomit-frame-pointer  -c RcppExports.cpp -o RcppExports.o
x86_64-pc-linux-gnu-g++ -std=gnu++11 -I"/usr/lib64/R/include" -DNDEBUG -I/usr/include/node/deps/v8/include -I/usr/include/v8 -I/usr/include/v8-3.14 -DV8_COMPRESS_POINTERS -I'/usr/lib64/R/library/R
cpp/include'   -fvisibility=hidden -fpic  -march=skylake -O3 -pipe -fomit-frame-pointer  -c bindings.cpp -o bindings.o
x86_64-pc-linux-gnu-g++ -std=gnu++11 -shared -L/usr/lib64/R/lib -Wl,-O1 -Wl,--as-needed -o V8.so RcppExports.o bindings.o -L/usr/include/node/libplatform -lv8 -lv8_libplatform -L/usr/lib64/R/lib -
lR
/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lv8
/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lv8_libplatform
collect2: error: ld returned 1 exit status
make: *** [/usr/lib64/R/share/make/shlib.mk:6: V8.so] Error 1
ERROR: compilation failed for package ‘V8’
```

So, all in all, 1) do you think that nodejs would be enough for installing V8 and 2) in case it is so, which changes should I do to the configure-vars to make it work?

More information is available at [stackoverflow](https://stackoverflow.com/questions/62910664/installing-v8-required-by-rstan-on-gentoo).

Thank you very much for your support.

**Comment by jeroen** [comment]
I have answered on SO: https://stackoverflow.com/a/63203853/318752

**Comment by jeroen** [comment]
The R package V8 simply needs libv8 headers and shared library. The best solution is to use the V8 engine from NodeJS, but this can only be done if NodeJS itself was built with the `--shared` option. I don't use Gentoo myself, but from the above I guess this is currently not the case.

You have to talk to @jer-gentoo , the maintainer of the nodejs package in Gentoo, and ask them to enable shared libnode. Below some references about this from Fedora and Debian, that might get you started:

 - Fedora: https://src.fedoraproject.org/rpms/nodejs/pull-request/4 and https://src.fedoraproject.org/rpms/R-V8
 - Debian: https://packages.debian.org/bullseye/libnode-dev and https://packages.debian.org/bullseye/r-cran-v8

If you can't get this to work, you could also build libv8 yourself, but I have to warn you this is pretty painful because upstream changes their API and build system every few weeks. 

Some working examples are:

 - Homebrew: https://github.com/homebrew/homebrew-core/blob/master/Formula/v8.rb
 - Arch: https://aur.archlinux.org/packages/v8-r/

**Comment by jeroen** [comment]
Hi @jer-gentoo, looking at [nodejs-14.7.0.ebuild](https://gitweb.gentoo.org/repo/gentoo.git/tree/net-libs/nodejs/nodejs-14.7.0.ebuild), would it be possible to build with `--shared` in the same way as e.g. Fedora's [nodejs.spec](https://src.fedoraproject.org/rpms/nodejs/blob/master/f/nodejs.spec) ?

**Comment by jer-gentoo** [comment]
I'll give that a go.

**Comment by jeroen** [comment]
@jer-gentoo thanks! LMK if I can help. Here is the debian repo: https://salsa.debian.org/js-team/nodejs/-/tree/master-12.x/debian

It looks a bit messy, but in effect what they do is:

 - Configure nodejs with `--shared`
 - Ship `libnode.so` and the headers a special package called `libnode-dev` (this may not be needed for Gentoo?)
 - Add some symlinks to make it easier for 3rd party software to find libv8:

```
/usr/include/v8                                                       ->  /usr/include/nodejs/deps/v8/include
/usr/lib/x86_64-linux-gnu/libv8.so                       ->  /usr/lib/x86_64-linux-gnu/libnode.so
/usr/lib/x86_64-linux-gnu/libv8_libplatform.so   ->  /usr/lib/x86_64-linux-gnu/libnode.so
/usr/lib/x86_64-linux-gnu/libv8_libsampler.so.   ->  /usr/lib/x86_64-linux-gnu/libnode.so
/usr/lib/x86_64-linux-gnu/llibv8_libbase.so.       ->  /usr/lib/x86_64-linux-gnu/libnode.so
```

This is because libnode bundles all of those v8 libraries, so applications can use the regular v8 linking flags.

**Comment by jer-gentoo** [comment]
Just adding `--shared` appears to build a library _instead of_ the `node` executable. I expected it to build an executable linked against that library but it does not appear to do that; setting `--shared` appears to be a binary choice between the expected executable and the library being installed.

**Comment by jeroen** [comment]
Hmm I'm pretty sure it is supposed to build both the shlib and the executable, as you would correctly expect. That is what the debian and fedora packages seem to do as well:
 - https://salsa.debian.org/js-team/nodejs/-/blob/master-12.x/debian/rules
 - https://src.fedoraproject.org/rpms/nodejs/blob/master/f/nodejs.spec

@sgallagher was there is something special you had to do to build the nodejs executable + shared library?

**Comment by jer-gentoo** [comment]
https://github.com/nodejs/node/blob/da4d8de9d09f98e6d81b9d5778fa44c26c25ec75/node.gyp#L271 shows that you get either one or the other: having an executable linked to a dynamic library is simply not considered in the build system.

**Comment by jeroen** [comment]
@kapouer how does debian build the nodejs executable + shared library?

**Comment by kapouer** [comment]
[with these flags](https://salsa.debian.org/js-team/nodejs/-/blob/master/debian/rules#L17) but honestly it's somewhat useless, as one pointed out, nodejs executable is tied to the version of the library it needs, so the split is artificial.

**Comment by jeroen** [comment]
Right, but the split does allow us to link to the v8 engine. I'm not sure why @jer-gentoo has found that building with `--shared` does not result in nodejs, only the shlib.

**Comment by sgallagher** [comment]
> Hmm I'm pretty sure it is supposed to build both the shlib and the executable, as you would correctly expect. That is what the debian and fedora packages seem to do as well:
> 
> * https://salsa.debian.org/js-team/nodejs/-/blob/master-12.x/debian/rules
> * https://src.fedoraproject.org/rpms/nodejs/blob/master/f/nodejs.spec
> 
> @sgallagher was there is something special you had to do to build the nodejs executable + shared library?

Yes, we had to incorporate a patch: https://src.fedoraproject.org/rpms/nodejs/blob/master/f/0002-Install-both-binaries-and-use-libdir.patch

**Comment by kapouer** [comment]
@sgallagher that patch looks odd to me. Why not just find out where the lib is built and install it from there.

**Comment by sgallagher** [comment]
> @sgallagher that patch looks odd to me. Why not just find out where the lib is built and install it from there.

Our preference is that the build-system's `make install` step should generally put things where they belong and `--libdir` is the standard mechanism for specifying that location.

But the more important part of that patch is the two calls to `action()`, one for the binary and another for the library.

**Comment by xfim** [comment]
I have tried the manual addition of symlinks as suggested by @jeroen , but still without luck.

@jer-gentoo , can we adapt that patch to the gentoo ebuild?

**Comment by makoshark** [comment]
I'm shifting this conversation over from: https://github.com/stan-dev/rstan/issues/831#issuecomment-684081217

@jeroen: This is a problem in any context in which users cannot install software as root regardless of the distribution. I think https://github.com/jeroen/V8/issues/94 is misleadingly titled in this regard.

I ran into the problem when I was trying to install rstan on the University of Washington's HPC system. The base distro on that system is RHEL but the environment is shared with all the users of the super computer and users do not have root or the ability to install software. The administrators are wary of installing a Javascript engine for one (small) set of users and prefer that we do it ourselves.

The problem is that V8 does not have a source distribution that can be built in the normal (`./configure --prefix=whatever; make; make install`) type way. Distributions have gotten around around this in various ways. Debian builds NodeJS as a shared library and then Debian adds a bunch of extra symlinks manually (outside of the normal NodeJS build process) so that LD can find the symbols for `libv8.so` and so on.

Although it's not common or convenient to have R packages that cannot install and build their own dependencies as part of the R installation process, I recognize that it does happen. That said, I know of no other R package that has dependencies for which there is no documented way to build from source and install the built packages without root.

Many of us run R on shared computers for which we do not have root and cannot install distribution packages. The question is: *what should we do?*

**Comment by makoshark** [comment]
Responding to the comment on https://github.com/stan-dev/rstan/issues/831#issuecomment-684112078:

> A lot of R/python packages have system dependencies which you need to install with apt or yum if you're on Linux. Installing v8 on RHEL is as simple as yum install v8-devel.

I know how to install packages as root. I explained that I do not have root and cannot install additional software that way.

> Alternatively you need to build everything from source, but as you found out that is not always trivial, these days libraries are very advanced and require complex tooling to build.

The problem is not that it's tricky to build software from source or that I do not know how to install software from packages or build complex software from source. I have been a Debian Developer for more than 20 years and and was part of the founding team for Ubuntu. I have built and installed Python, R, and many other packages from source on the HPC system in question and they are running fine as simple [environment modules](https://modules.readthedocs.io/en/latest/index.html).

The problem is that there appears to be no maintained source code with build scripts that will build and install the library you depend on (`libv8.so`) with *any* toolchain that doesn't involve installing a whole separate packaging system (like conda or linuxbrew), nor any instructions on how to build and install it from source for use in library form that your package requires it. Every package in every distro I've found hacks around things to provide the symbol you want in the place you're looking for in through packaging work they do in a way that is generally not portable to a source-only system.

If I'm missing something, please tell me.

**Comment by JanMarvin** [comment]
With v8 it's `gn gen --args="whatever"; ninja`. can't you clone depot_tools locally and run `fetch v8`. tar the folder and push it to the hpc. run `gn gen` and `ninja` (both are part of depot_tools and require python) and copy libv8.so from the build folder? That's basically what the arch pkg does (minus the hpc part ofc). it doesn't require anything aside from python and git for the fetch part

**Comment by jeroen** [comment]
The way to build v8 is documented in the v8 source and on v8.dev. It's just not as easy as `./configure make install` because it requires some custom libs and build utilities. But it is not impossible, some examples of actively maintained scripts by the respective package maintainers:

 - Arch linux (by @JanMarvin): https://github.com/JanMarvin/v8-R/blob/master/PKGBUILD
 - Linuxbrew: https://github.com/homebrew/linuxbrew-core/blob/master/Formula/v8.rb
 - msys2 (windows): https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-v8/PKGBUILD

**Comment by gsgxnet** [comment]
> With v8 it's `gn gen --args="whatever"; ninja`. can't you clone depot_tools locally and run `fetch v8`. tar the folder and push it to the hpc. run `gn gen` and `ninja` (both are part of depot_tools and require python) and copy libv8.so from the build folder? That's basically what the arch pkg does (minus the hpc part ofc). it doesn't require anything aside from python and git for the fetch part

I have `depot_tools`and `fetch v8`worked. But Jan, which `args` would I have to set for compiling on openSUSE?  
See #103

**Comment by JanMarvin** [comment]
If you're feeling lucky. I have a branch 'static' here: https://github.com/JanMarvin/V8/tree/static which searches and links with 'inst/v8'. This folder can be obtained from a V8 statically linked monolith x86_64 build found over here: https://github.com/JanMarvin/v8-static/releases/tag/8.6.395.17 (either build it using the instructions from the PKGBUILD or simply extract the v8 folder from the binary attached to the release).

If you do, please let me know.

**Comment by gsgxnet** [comment]
Jan, 
thanks that works - at least for the moment, how to cope with updates - we will see.  
To document in more detail how I did the install:
`git clone https://github.com/JanMarvin/V8.git`  
open that folder as a project in RStudio.
On the git tab there activate the static repo. 
download your  [static monolith](https://github.com/JanMarvin/v8-static/releases/tag/8.6.395.17)
extract it, move the v8 folder from there as new v8 subfolder of the `inst` folder within the cloned repo
run a Clean and Rebuild within RStudio
success:
```
library(V8)
Using V8 engine 8.6.395.17
```

**Comment by jeroen** [comment]
Added an option to the master branch to automatically download libv8. This should allow installation on any Linux system with at least gcc-5. To test this, run in R:

```r
Sys.setenv(DOWNLOAD_STATIC_LIBV8 = 1)
remotes::install_github("jeroen/V8")
```

**Comment by xfim** [comment]
This works perfectly. Excellent. Thank you very much @jeroen .

**Comment by Kabouik** [comment]
> Added an option to the master branch to automatically download libv8. This should allow installation on any Linux system with at least gcc-5. To test this, run in R:
> 
> ```r
> Sys.setenv(DOWNLOAD_STATIC_LIBV8 = 1)
> install.packages("V8")
> ```

Thanks, your post was a lifesaver on Solus where V8 isn't available!
